### ISSUE TITLE
[Enhancement] Adjust the collision of the Hauler to allow players to ride it.

### ISSUE THREAD

**Issue by Mr-Foxtrot** [Moffein/Potmobile#1]
It's called hauler, yet it can't haul.
:(

Currently the collision/friction doesn't allow carrying people on either vehicle, so adjusting it to allow such would genuinely make these more fun in multiplayer.

**Comment by Moffein** [comment]
Updated the mod, collision knockback is now disabled on teammates so it should be a bit easier to ride them (though I'd imagine it'd still be easy to fall off).
I can also recommend https://thunderstore.io/package/Mico27/RideMeExtended/ as I've confirmed that it works with this mod.

**Comment by Mr-Foxtrot** [comment]
Ah sweet, thanks for the update and the recommendation!
