### ISSUE TITLE
Potmobile & Hauler UpdateWheelParameter NRE spam

### ISSUE THREAD

**Issue by Phreelosu** [Moffein/Potmobile#6]
[LogOutput.log](https://github.com/user-attachments/files/17444748/LogOutput.log)

this is extremely edge case, and I'm not expecting a fix but whenever Potmobiles and Haulers are chosen as enemies in Void Fields, once the cell destroys all bodies this NRE spam happens until the next cell is started

**Comment by Moffein** [comment]
Released an update, let me know if it fixed the issue.

**Comment by Phreelosu** [comment]
[LogOutput.log](https://github.com/user-attachments/files/17458948/LogOutput.log)

its partially fixed, now ApplyWheelForces is the one spamming NREs LOL


EDIT: [LogOutput.log](https://github.com/user-attachments/files/17458976/LogOutput.log)

it seems to be cascading of an NRE as well, as HoverVehicleMotor.FixedUpdate is spamming NREs too

**Comment by Moffein** [comment]
Uploaded another fix

**Comment by Phreelosu** [comment]
that fixed it, thank you very much
